version: '3.9'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: kyara-dev
      POSTGRES_USER: kyara-dev
      POSTGRES_PASSWORD: kyara_pass_dev
    ports:
      - 9001:5432
