// <auto-generated />
using System;
using Kyara.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kyara.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240228184215_CharacterSeeding")]
    partial class CharacterSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kyara.Api.Domain.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9873b8fb-561b-4492-aa7f-03d3a7202c45"),
                            Image = "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/2948a0a5-4bde-4290-94ed-edf158befd07/width=450/Isla0.jpeg",
                            Name = "Isla",
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("7dbc50f9-f4a6-4f0d-a192-4d1f58e5928c"),
                            Image = "https://i1.sndcdn.com/artworks-000133617614-ywuyai-t500x500.jpg",
                            Name = "Akame",
                            Rating = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
